# Generated by Django 4.1 on 2024-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.project"
            ),
        ),
    ]
